import type { FormationType, MapMode, OrderStatus, OrderType, TimeOfDay, UnitType, Weather } from './models/game'

export type Language='ko'|'en'

const ko={
  operation:'작전명',title:'무난하고 빠른 전면전',classified:'기밀',ally:'아군',enemy:'적군',sites:'거점',contacts:'접촉',visible:'가시',lost:'소실',day:'제 {day}일',phase:'PHASE 8',
  unitIntel:'적군 정보',singleUnit:'개별 부대',combatPower:'전투 전력',combatStatus:'전투 상태',weaponRange:'무기 사거리',currentTarget:'현재 목표',nextShot:'다음 사격',armor:'장갑',position:'현재 위치',none:'없음',selectAll:'전체 선택',hold:'위치 사수',focus:'부대로 이동',multiSelect:'다중 선택',unitsSelected:'{count}개 부대 선택',formationStatus:'편대 상태',independentGroup:'독립 그룹',multiHelp:'우클릭으로 그룹 이동하거나 편대를 창설하십시오',createFormation:'편대 창설',selectedFormation:'선택 편대',currentFormation:'현재 대형',formationSpeed:'편대 속도',cohesionError:'결속 오차',chooseFormation:'대형 선택',disband:'편대 해체',
  attack:'공격',move:'이동',follow:'추종',recon:'지역 정찰',search:'수색',reorganize:'재편성',orderQueue:'명령 큐',active:'ACTIVE',noOrders:'활성 명령 없음',cancelOrder:'현재 명령 취소',recentOrders:'최근 명령 기록',
  aiStatus:'상태',aiObjective:'목표',forceRatio:'전력비',lastDecision:'최근 판단',observing:'관측 중',initialAnalysis:'초기 전장 분석',decisionCycle:'판단 주기 {seconds}s · 명령 즉시 실행',
  mission:'임무',missionLimit:'작전 제한 시간',hoursMinutes:'{hours}시간 {minutes}분',defending:'방어 유지 중 · 적 점령 시 즉시 실패',save:'저장',load:'불러오기',restart:'재시작',closeMission:'미션 창 닫기',
  plain:'평야',forest:'삼림',river:'하천',road:'도로',strategicSite:'전략 거점',paused:'작전 일시정지',pauseHelp:'카메라와 명령 입력은 활성 상태입니다',missionComplete:'MISSION COMPLETE',missionFailed:'MISSION FAILED',afterAction:'AFTER ACTION REVIEW',operationTime:'작전 시간 {hours}시간 {minutes}분 · 아군 손실 {allies}개 부대 · 적 전투 불능 {enemies}개 부대',restartScenario:'시나리오 다시 시작',
  clickFollow:'따라갈 부대를 클릭하십시오',clickAttack:'공격할 적 또는 마지막 확인 위치를 클릭하십시오',clickRecon:'정찰할 지역을 클릭하십시오',clickSearch:'수색할 지역을 클릭하십시오',clickDestination:'목적지를 클릭하십시오',cancel:'취소',commandNet:'COMMAND NET',battleNet:'전투 지휘망 / CH. 04',mapMode:'지도 모드',supplyNet:'보급망',resupply:'재보급',pause:'정지',enemySelect:'적 선택',completeSim:'COMPLETE SIM',events:'작전 이벤트',liveFeed:'LIVE FEED',language:'EN',
  weather:{CLEAR:'맑음',RAIN:'강우'} as Record<Weather,string>,timeOfDay:{NIGHT:'야간',MORNING:'아침',DAY:'주간',EVENING:'저녁'} as Record<TimeOfDay,string>,mapModes:{NORMAL:'일반',SUPPLY:'보급',INTELLIGENCE:'정보',COMMAND:'지휘',COMBAT:'전투'} as Record<MapMode,string>,
  orders:{move:'이동',hold:'위치 사수',follow:'추종',reorganize:'재편성',changeFormation:'대형 변경',attack:'공격',recon:'정찰',search:'수색',resupply:'재보급'} as Record<OrderType,string>,
  orderStatus:{queued:'대기열',transmitting:'전송 중',received:'수신 완료',preparing:'준비 중',executing:'실행 중',completed:'완료',cancelled:'취소'} as Record<OrderStatus,string>,
  formations:{line:'횡대',column:'종대',wedge:'쐐기'} as Record<FormationType,string>,unitTypes:{보병:'보병',기계화:'기계화',기갑:'기갑',포병:'포병',정찰:'정찰',공병:'공병'} as Record<UnitType,string>,
  missionName:'무난하고 빠른 전면전',briefing:'서부 교두보를 방어하면서 아른하임 지휘소와 칼슈타트 탄약창을 확보하고 적 기동단을 무력화하십시오.',objectives:{'defend-hq':['서부 전선 지휘소 방어','주 지휘소를 적에게 빼앗기지 마십시오.'],'capture-arnheim':['아른하임 전쟁기지 점령','적 전선 지휘의 중심을 확보하십시오.'],'capture-ammo':['칼슈타트 탄약창 점령','적 전선의 탄약 보급을 차단하십시오.'],'destroy-mobile':['적 기동단 무력화','적 전차·정찰 기동부대를 전투 불능으로 만드십시오.']} as Record<string,[string,string]>,
}

const en={
  ...ko,operation:'OPERATION',title:'A Straightforward Blitz',classified:'CLASSIFIED',ally:'ALLIES',enemy:'ENEMY',sites:'SITES',contacts:'CONTACTS',visible:'VISIBLE',lost:'LOST',day:'DAY {day}',
  unitIntel:'ENEMY INTEL',singleUnit:'UNIT',combatPower:'COMBAT STRENGTH',combatStatus:'COMBAT STATUS',weaponRange:'WEAPON RANGE',currentTarget:'CURRENT TARGET',nextShot:'NEXT SHOT',armor:'ARMOR',position:'POSITION',none:'NONE',selectAll:'SELECT FORMATION',hold:'HOLD POSITION',focus:'FOCUS UNIT',multiSelect:'MULTI SELECT',unitsSelected:'{count} UNITS SELECTED',formationStatus:'FORMATION STATUS',independentGroup:'INDEPENDENT GROUP',multiHelp:'Right-click to move as a group, or create a formation.',createFormation:'CREATE FORMATION',selectedFormation:'FORMATION',currentFormation:'CURRENT FORMATION',formationSpeed:'FORMATION SPEED',cohesionError:'COHESION ERROR',chooseFormation:'FORMATION TYPE',disband:'DISBAND FORMATION',
  attack:'ATTACK',move:'MOVE',follow:'FOLLOW',recon:'RECON AREA',search:'SEARCH',reorganize:'REORGANIZE',orderQueue:'ORDER QUEUE',noOrders:'NO ACTIVE ORDERS',cancelOrder:'CANCEL CURRENT ORDER',recentOrders:'RECENT ORDER HISTORY',
  aiStatus:'STATUS',aiObjective:'OBJECTIVE',forceRatio:'FORCE RATIO',lastDecision:'LAST DECISION',observing:'OBSERVING',initialAnalysis:'INITIAL BATTLEFIELD ANALYSIS',decisionCycle:'DECISION CYCLE {seconds}s · ORDERS EXECUTE IMMEDIATELY',
  mission:'MISSION',missionLimit:'TIME REMAINING',hoursMinutes:'{hours}h {minutes}m',defending:'Holding · mission fails if captured',save:'SAVE',load:'LOAD',restart:'RESTART',closeMission:'Close mission panel',
  plain:'PLAIN',forest:'FOREST',river:'RIVER',road:'ROAD',strategicSite:'STRATEGIC SITE',paused:'OPERATION PAUSED',pauseHelp:'Camera and command input remain active.',operationTime:'Operation time {hours}h {minutes}m · Allied losses {allies} · Enemy disabled {enemies}',restartScenario:'RESTART SCENARIO',
  clickFollow:'Click the unit to follow',clickAttack:'Click an enemy or last known position',clickRecon:'Click an area to recon',clickSearch:'Click an area to search',clickDestination:'Click a destination',cancel:'CANCEL',battleNet:'BATTLE COMMAND NET / CH. 04',mapMode:'MAP MODE',supplyNet:'SUPPLY',resupply:'RESUPPLY',pause:'PAUSE',enemySelect:'SELECT ENEMY',language:'한국어',
  events:'OPERATION EVENTS',weather:{CLEAR:'CLEAR',RAIN:'RAIN'} as Record<Weather,string>,timeOfDay:{NIGHT:'NIGHT',MORNING:'MORNING',DAY:'DAY',EVENING:'EVENING'} as Record<TimeOfDay,string>,mapModes:{NORMAL:'NORMAL',SUPPLY:'SUPPLY',INTELLIGENCE:'INTELLIGENCE',COMMAND:'COMMAND',COMBAT:'COMBAT'} as Record<MapMode,string>,
  orders:{move:'MOVE',hold:'HOLD',follow:'FOLLOW',reorganize:'REORGANIZE',changeFormation:'CHANGE FORMATION',attack:'ATTACK',recon:'RECON',search:'SEARCH',resupply:'RESUPPLY'} as Record<OrderType,string>,
  orderStatus:{queued:'QUEUED',transmitting:'TRANSMITTING',received:'RECEIVED',preparing:'PREPARING',executing:'EXECUTING',completed:'COMPLETED',cancelled:'CANCELLED'} as Record<OrderStatus,string>,
  formations:{line:'LINE',column:'COLUMN',wedge:'WEDGE'} as Record<FormationType,string>,unitTypes:{보병:'INFANTRY',기계화:'MECHANIZED',기갑:'ARMORED',포병:'ARTILLERY',정찰:'RECON',공병:'ENGINEERS'} as Record<UnitType,string>,
  missionName:'A Straightforward Blitz',briefing:'Defend the western bridgehead, capture the Arnhem command post and Kalstadt ammunition depot, and neutralize the enemy mobile group.',objectives:{'defend-hq':['Defend Western Command Post','Do not allow the enemy to capture the main command post.'],'capture-arnheim':['Capture Arnhem Command Post','Secure the center of enemy frontline command.'],'capture-ammo':['Capture Kalstadt Ammo Depot','Cut off the enemy frontline ammunition supply.'],'destroy-mobile':['Neutralize Enemy Mobile Group','Disable the enemy tank and reconnaissance units.']} as Record<string,[string,string]>,
}

export const COPY={ko:{...ko,briefing:'아른헤임 기지와 칼슈타트 보급소를 점령하십시오. 보급소에서 탄약·연료·전력을 회복할 수 있습니다.',objectives:{'capture-arnheim':['아른헤임 기지 점령','아른헤임 기지를 아군 거점으로 확보하십시오.'],'capture-ammo':['칼슈타트 보급소 점령','칼슈타트 보급소를 확보해 재보급에 활용하십시오.']} as Record<string,[string,string]>},en:{...en,briefing:'Capture Arnheim Base and Kalstadt Supply Depot. Supply depots restore ammunition, fuel, and strength.',objectives:{'capture-arnheim':['Capture Arnheim Base','Secure Arnheim Base for your forces.'],'capture-ammo':['Capture Kalstadt Supply Depot','Secure the depot and use it to resupply.']} as Record<string,[string,string]>}}
const englishNames:Record<string,string>={
  '서부 전선 보급소':'Western Front Supply Depot','아른헤임 기지':'Arnheim Base',
  '동부 장거리 통신소':'Eastern Long-range Communications Station','남부 집단군 지휘소':'Southern Army Group Command Post','적 제1전차중대':'Enemy 1st Tank Company',
  '하르덴':'Harden','벨로프':'Belov','칼슈타트':'Kalstadt','아른하임':'Arnheim','로젠':'Rosen','드라벤':'Draven','에버하임':'Everheim','노르트펠트':'Nordfeld','브뤼크':'Bruck','잘츠도르프':'Salzdorf','발데른':'Waldern','그라우펠트':'Graufeld','오스트하임':'Ostheim','카이저브뤼크':'Kaiserbruck','하겐':'Hagen','엘렌도르프':'Ellendorf','미텔발트':'Mittelwald','크로이츠':'Kreuz','쥐트하펜':'Sudhafen','바렌':'Waren','웨스트마르크':'Westmark',
  '린덴':'Linden','오버탈':'Obertal','슈타인':'Stein','발트호프':'Waldhof','클라인브뤼크':'Kleinbruck','호헨':'Hohen','도르프':'Dorf','아이헨':'Eichen','노이탈':'Neutal','펠젠':'Felsen','라우흐':'Rauch','알트브뤼크':'Altbruck','쾨니히스펠트':'Konigsfeld','잘름':'Salm','브루넨':'Brunnen',
  '서북 삼림':'Northwestern Forest','북동 수림':'Northeastern Woods','동남 숲':'Southeastern Forest','서남 숲':'Southwestern Forest','검은 숲':'Blackwood','동부 대삼림':'Great Eastern Forest','남부 소나무숲':'Southern Pines','강변 수림':'Riverside Woods','발트마르크 숲':'Waldmark Forest','전나무 능선':'Fir Ridge','심동부 숲':'Deep Eastern Forest','녹색 지대':'Green Belt','늑대 숲':'Wolfwood','남부 변경림':'Southern March Forest','하부 소나무숲':'Lower Pines','국경 수림':'Border Woods',
  '고지 204':'Hill 204','회색 구릉':'Grey Hills','독수리 능선':'Eagle Ridge','남부 고지':'Southern Heights','발데른 능선':'Waldern Ridge','철십자 고지':'Iron Cross Heights','동부 구릉':'Eastern Hills','황혼 능선':'Twilight Ridge','서부 고원':'Western Plateau','라우엔 호':'Lake Rauen','에르렌 호':'Lake Erlen','검은 호수':'Black Lake','남부 호':'Southern Lake',
  '서부 전선 지휘소':'Western Front Command Post','전쟁기지':'Command Post','장거리 통신소':'Long-range Communications Station','방공 레이더':'Air Defense Radar','철도 조차장':'Rail Yard','집단군 지휘소':'Army Group Command Post','군수 보급창':'Logistics Depot','연료 저장소':'Fuel Depot','야전병원':'Field Hospital','공군기지':'Airbase','탄약창':'Ammo Depot','보급소':'Supply Depot','철도역':'Rail Station','레이더':'Radar',
  '적 전선단':'Enemy Frontline Group','적 기동단':'Enemy Mobile Group','적 지원단':'Enemy Support Group','적 독립 정찰소대':'Enemy Independent Recon Platoon','적 국경수비중대':'Enemy Border Guard Company','적 독립 공병중대':'Enemy Independent Engineer Company','적 독립 포병포대':'Enemy Independent Artillery Battery',
  '위치 사수':'Holding Position','이동 중':'Moving','대형 정렬':'Forming Up','재편성':'Reorganizing','재보급 중':'Resupplying','대기':'Idle','여단':'Brigade','연대':'Regiment','대대':'Battalion','중대':'Company','소대':'Platoon','기동편대':'Mobile Formation','기갑':'Armored','기계화':'Mechanized','보병':'Infantry','포병':'Artillery','정찰':'Recon','공병':'Engineer',
  '농경지':'Farmland','평야':'Plain','삼림':'Forest','하천':'River','도로':'Road','도시':'City','교량':'Bridge','탄약':'Ammo','연료':'Fuel','대전구':'Grand Theater','전구':'Theater','전역':'Operational','지역':'Regional','전술':'Tactical',
  '전체 선택':'Select All','선택 해제':'Selection Cleared','선택':'Selected','더블클릭하면':'Double-click to select','목적지 도착':'Destination Reached','전투 불능':'Disabled','사격':'Fired','피격':'Hit','전력':'Strength','진입':'Entered','적 접촉 탐지':'Enemy Contact Detected','적 접촉 소실':'Enemy Contact Lost','적 식별 완료':'Enemy Identified','적 접촉 재확인':'Enemy Contact Reacquired','마지막 위치 기록':'Last Position Recorded','적 접촉':'Enemy Contact','마지막 확인':'Last Seen','분 전':'Minutes Ago','미확인 적':'Unknown Enemy','적 지휘부':'Enemy Command','방어 구역 불규칙 순찰':'Irregular Defensive Patrol',
  '명령 실행':'Order Executed','명령 완료':'Order Completed','명령 취소':'Order Cancelled','명령':'Order','공격':'Attack','이동':'Move','추종':'Follow','수색':'Search','재보급':'Resupply','대형 변경':'Change Formation','대기열 추가':'Added to Queue','실행':'Executed','취소':'Cancelled','창설 완료':'Created','창설':'Created','해체 완료':'Disbanded','해체':'Disbanded','개 부대':'Units',
  '부대를 선택해 이동 명령을 내리십시오':'Select a unit and issue a move order','작전 상황 저장 완료':'Game Saved','저장된 작전 상황 불러오기 완료':'Game Loaded','저장된 작전 상황이 없습니다':'No Saved Game','저장 데이터가 손상되었습니다':'Saved Data Is Corrupted','시나리오 재시작 · 작전 통제권 인계':'Scenario Restarted · Command Transferred','작전 일시정지':'Operation Paused','작전 재개':'Operation Resumed','시간 배율':'Time Scale','작전 시간 속도':'Simulation Speed','보급망 전술 오버레이 전환':'Supply Overlay Toggled','지도 모드':'Map Mode','명령 입력 취소':'Command Input Cancelled','연결된 보급 거점이 없습니다':'No Connected Supply Point',
  '보급망 단절':'Supply Disconnected','보급망 연결':'Supply Connected','보급 위험':'Critical Supply','탄약 부족':'Low Ammo','연료 부족':'Low Fuel','재보급 시작':'Resupply Started','재보급 완료':'Resupply Complete','군수품 노획':'Supplies Looted','점령':'Captured','아군':'Allies','적군':'Enemy',
}
const nameEntries=Object.entries(englishNames).sort((a,b)=>b[0].length-a[0].length)
export function translateText(text:string,language:Language):string{
  if(language==='ko')return text
  let result=text.replace(/(적 )?제(\d+)(기갑|기계화|보병|포병|정찰|공병)(여단|연대|대대|중대|소대)/g,(_,enemy:string|undefined,n:string,type:string,size:string)=>`${enemy?'Enemy ':''}${n}${n.endsWith('11')||n.endsWith('12')||n.endsWith('13')?'th':n.endsWith('1')?'st':n.endsWith('2')?'nd':n.endsWith('3')?'rd':'th'} ${englishNames[type]} ${englishNames[size]}`).replace(/제(\d+)기동편대/g,'Mobile Formation $1')
  for(const [source,target] of nameEntries)result=result.replaceAll(source,target)
  return result
}
export type Copy=typeof ko
export const format=(value:string,values:Record<string,string|number>)=>Object.entries(values).reduce((result,[key,replacement])=>result.replace(`{${key}}`,String(replacement)),value)
